NIE/CSE/urls.py
from django.urls import path
from CSE import views
from CSE.views import StuList,Forms, StudentDetail, StudentUpdate, StudentDelete

app_name ='CSE'

urlpatterns = [
 path('index', views.index, name = 'index'),
path('products', views.products, name = 'products'),
path('service', views.service, name = 'service'),
path('contacts', views.contacts, name = 'contacts'),
path('basic', views.basic, name = 'basic'),
path('studentList', views.studentList, name = 'studentList'),

path('', StuList.as_view(), name = 'list'),
path('forms', Forms.as_view(), name = 'forms'),
path('<pk>/detail', StudentDetail.as_view(), name = 'detail'),
path('<pk>/update', StudentUpdate.as_view(), name = 'update'),
path('<pk>/delete', StudentDelete.as_view(), name = 'delete'),




]

NIE/CSE/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=50)
    department = models.CharField(max_length=30)
    college_name = models.CharField(max_length=30)
    rollnumber = models.IntegerField()
    def __str__(self):
        return self.name

NIE/CSE/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request,'index.html')

def products(request):
    name = 'raju'
    department = 'CSE'
    college_name = 'NIE'
    roll_number = 60145
    context = {'name': name, 'c_name': college_name, 'd_name': department, 'r_number':roll_number}
    return render(request,'products.html', context)

def service(request):
    return render(request,'service.html')

def contacts(request):
    return render(request,'contacts.html')


def basic(request):
    return render(request,'basic.html')

# FBV - Listview
from CSE.models import Student
def studentList(request):
    students = Student.objects.all()
    context = {'students':students}
    return render(request,'studentList.html',context)

from CSE.models import Student
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

class StuList(ListView):
    model = Student
    template_name = 'CBV/list.html'


class Forms(CreateView):
    model = Student
    fields = "__all__"
    template_name = 'CBV/forms.html'
    success_url = '/'


class StudentDetail(DetailView):
    model = Student
    template_name = 'CBV/detail.html'

class StudentUpdate(UpdateView):
    model = Student
    fields = '__all__'
    template_name = 'CBV/update.html'
    success_url = '/'
    
class StudentDelete(DeleteView):
    model = Student
    template_name = 'CBV/delete.html'
    success_url = '/'

NIE/templates/basic.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  
{% comment %} navbar {% endcomment %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'CSE:index' %}">Home</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'CSE:products' %}">Products</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'CSE:service' %}">Service</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link" href="{% url 'CSE:contacts' %}">Contacts</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'CSE:studentList' %}">studentList</a>
          </li>
         
          <li class="nav-item">
            <a class="nav-link" href="{% url 'CSE:list' %}">FBV</a>
          </li>
          
                      
      </div>
    </div>
  </nav>

{% block content %}
{% endblock %}
</body>
</html>

NIE/templates/basic1.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>
  <body>
   
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="#">Products</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="#">Service</a>
              </li>
              
              <li class="nav-item">
                <a class="nav-link" href="#">Contacts</a>
              </li>
              
                          
          </div>
        </div>
      </nav>
{% comment %} navbar {% endcomment %}
{% comment %} button {% endcomment %}


<button type="button" class="btn btn-primary">Primary</button>
<button type="button" class="btn btn-secondary">Secondary</button>
<button type="button" class="btn btn-success">Success</button>
<button type="button" class="btn btn-danger">Danger</button>
<button type="button" class="btn btn-warning">Warning</button>
<button type="button" class="btn btn-info">Info</button>
<button type="button" class="btn btn-light">Light</button>
<button type="button" class="btn btn-dark">Dark</button>

<button type="button" class="btn btn-link">Link</button>

{% comment %} card {% endcomment %}
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>

{% comment %} alerts {% endcomment %}
<div class="alert alert-primary" role="alert">
  A simple primary alert—check it out!
</div>
<div class="alert alert-secondary" role="alert">
  A simple secondary alert—check it out!
</div>
<div class="alert alert-success" role="alert">
  A simple success alert—check it out!
</div>
<div class="alert alert-danger" role="alert">
  A simple danger alert—check it out!
</div>
<div class="alert alert-warning" role="alert">
  A simple warning alert—check it out!
</div>
<div class="alert alert-info" role="alert">
  A simple info alert—check it out!
</div>
<div class="alert alert-light" role="alert">
  A simple light alert—check it out!
</div>
<div class="alert alert-dark" role="alert">
  A simple dark alert—check it out!
</div>

{% comment %} close {% endcomment %}
<button type="button" class="btn-close" aria-label="Close">
 {% comment %} floatinglables {% endcomment %}
 <div class="form-floating mb-3">
  <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
  <label for="floatingInput">Email address</label>
</div>
<div class="form-floating">
  <input type="password" class="form-control" id="floatingPassword" placeholder="Password">
  <label for="floatingPassword">Password</label>
</div>

{% comment %} spnires {% endcomment %}
<div class="spinner-grow text-primary" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-grow text-secondary" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-grow text-success" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-grow text-danger" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-grow text-warning" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-grow text-info" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-grow text-light" role="status">
  <span class="visually-hidden">Loading...</span>
</div>
<div class="spinner-grow text-dark" role="status">
  <span class="visually-hidden">Loading...</span>
</div>

{% comment %} popover {% endcomment %}
<button type="button" class="btn btn-lg btn-danger" data-bs-toggle="popover" data-bs-title="Popover title" data-bs-content="And here's some amazing content. It's very engaging. Right?">Click to toggle popover</button>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

NIE/templates/contacts.html
{% extends 'basic.html' %}

{% block content %}

<h1>this is a contacts page.</h1>
{% endblock %}

NIE/templates/index.html
{% extends 'basic.html' %}

{% block content %}

<h1>Welcome to web development</h1>
{% endblock %}

NIE/templates/products.html
{% extends 'basic.html' %}

{% block content %}

<h1>This is a products page.</h1>
NAME:{{name}}<br>
College name:{{c_name}}<br>
Depatment name:{{d_name}}<br>
Roll number:{{r_number}}<br>




{% endblock %}

NIE/templates/service.html
{% extends 'basic.html' %}

{% block content %}

<h1>this is a service page.</h1>
{% endblock %}

NIE/templates/studentList.html
{% include "basic.html" %}

 {% block content %}

 {% for student in students %}
 
 Name:{{student.name}}<br>
 Department: {{student.department}}<br>
 College Name: {{student.college_name}}<br>
 Roll number: {{student.rollnumber}}<br>
 <hr>



 {% endfor %}
 
 {% endblock %}